name: Build test and coverage (reusable)

on:
  workflow_call:
    inputs:
      coverage:
        required: true
        type: boolean
    secrets:
      codecov:

jobs:
  build_test_and_coverage:
    runs-on: ubuntu-latest
    services:
      gmocky:
        image: joakimribier/mockapic
        env:
          MOCKAPIC_PORT: 3333
        ports:
          - 3333:3333

    steps:
    - name: Docker
      run: docker container ls -a

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out
      env:
        ENV_MODE: ci

    - name: Upload coverage to Codecov
      if: ${{ inputs.coverage }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.codecov }} # required
        verbose: true # optional (default = false)